openapi: 3.0.0
info:
  title: API Open Banking
  description: API para operações de Open Banking, incluindo consulta de saldo, dados cadastrais, extrato, transferência PIX e consulta de limite de crédito.
  version: "1.2.0"
servers:
  - url: http://localhost:8080
    description: Servidor local para desenvolvimento e testes

paths:
  /open-banking/saldo:
    get:
      summary: Consulta o saldo disponível de uma conta bancária
      parameters:
        - name: conta
          in: query
          required: true
          description: Identificador da conta bancária
          schema:
            type: string
      responses:
        '200':
          description: Saldo encontrado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContaDTO'
        '404':
          description: Conta não encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErroResponse'

  /open-banking/dados-cliente:
    get:
      summary: Consulta dados cadastrais do cliente
      parameters:
        - name: cliente
          in: query
          required: true
          description: Identificador do cliente
          schema:
            type: string
      responses:
        '200':
          description: Dados do cliente retornados com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClienteDTO'
        '404':
          description: Cliente não encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErroResponse'

  /open-banking/contas-cliente:
    get:
      summary: Consulta todas as contas do cliente
      parameters:
        - name: cliente
          in: query
          required: true
          description: Identificador do cliente
          schema:
            type: string
      responses:
        '200':
          description: Lista de contas retornada com sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ContaDTO'

  /open-banking/transacoes:
    get:
      summary: Consulta o extrato da conta
      parameters:
        - name: conta
          in: query
          required: true
          description: Identificador da conta bancária
          schema:
            type: string
      responses:
        '200':
          description: Extrato retornado com sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TransacaoDTO'
        '404':
          description: Conta não encontrada ou sem transações
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErroResponse'

  /open-banking/pix/transferencias:
    post:
      summary: Realiza uma simulação de transferência PIX
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransferenciaPixRequest'
      responses:
        '200':
          description: Transferência realizada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransferenciaPixResponse'
        '400':
          description: Erro na solicitação de transferência PIX
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErroResponse'
        '404':
          description: Conta de origem ou destino não encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErroResponse'

  /open-banking/limite-credito:
    get:
      summary: Consulta limite de crédito pré-aprovado
      parameters:
        - name: cliente
          in: query
          required: true
          description: Identificador do cliente
          schema:
            type: string
      responses:
        '200':
          description: Limite de crédito retornado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LimiteCreditoDTO'
        '404':
          description: Cliente não encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErroResponse'

components:
  schemas:
    ContaDTO:
      type: object
      properties:
        contaId:
          type: string
          example: "123"
        tipoConta:
          type: string
          example: "Corrente"
        saldoDisponivel:
          type: number
          format: double
          example: 1500.00
        moeda:
          type: string
          example: "BRL"

    ClienteDTO:
      type: object
      properties:
        clienteId:
          type: string
          example: "c123"
        nome:
          type: string
          example: "João da Silva"
        cpf:
          type: string
          example: "123.456.789-00"
        email:
          type: string
          example: "joao@email.com"

    TransacaoDTO:
      type: object
      properties:
        data:
          type: string
          format: date
          example: "2025-06-12"
        descricao:
          type: string
          example: "Pagamento de boleto"
        valor:
          type: number
          format: double
          example: -200.00
        moeda:
          type: string
          example: "BRL"

    TransferenciaPixRequest:
      type: object
      required:
        - contaOrigemId
        - contaDestinoId
        - valor
        - moeda
      properties:
        contaOrigemId:
          type: string
          example: "123"
        contaDestinoId:
          type: string
          example: "124"
        valor:
          type: number
          format: double
          example: 200.00
        moeda:
          type: string
          example: "BRL"

    TransferenciaPixResponse:
      type: object
      properties:
        transactionId:
          type: string
          example: "c4f1b2f9-8a1e-4db0-9a1a-5d6e2a7b8c9d"
        mensagem:
          type: string
          example: "Transferência PIX realizada com sucesso"
        contaOrigemId:
          type: string
          example: "123"
        contaDestinoId:
          type: string
          example: "124"
        valor:
          type: number
          format: double
          example: 200.00
        moeda:
          type: string
          example: "BRL"

    LimiteCreditoDTO:
      type: object
      properties:
        clienteId:
          type: string
          example: "c123"
        limiteCredito:
          type: number
          format: double
          example: 15000.00
        moeda:
          type: string
          example: "BRL"
        taxaJuros:
          type: number
          format: double
          example: 3.50

    ErroResponse:
      type: object
      properties:
        codigoErro:
          type: string
          example: "404"
        mensagem:
          type: string
          example: "Recurso não encontrado."
